# Generated by Django 5.2.8 on 2026-06-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdr22', '0012_configuracionsistema_ciudad_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='whatsapp_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='whatsapp_numero_prueba',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='whatsapp_template_factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='whatsapp_template_language',
            field=models.CharField(default='es_CO', max_length=10),
        ),
    ]
